USE [BDINVENTARIO]
GO

/****** Object:  Table [dbo].[MOV_INVENTARIO]    Script Date: 27/11/2024 22:57:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MOV_INVENTARIO](
	[COD_CIA] [varchar](5) NOT NULL,
	[COMPANIA_VENTA_3] [varchar](5) NOT NULL,
	[ALMACEN_VENTA] [varchar](10) NOT NULL,
	[TIPO_MOVIMIENTO] [varchar](2) NOT NULL,
	[TIPO_DOCUMENTO] [varchar](2) NOT NULL,
	[NRO_DOCUMENTO] [varchar](50) NOT NULL,
	[COD_ITEM_2] [varchar](50) NOT NULL,
	[PROVEEDOR] [varchar](100) NULL,
	[ALMACEN_DESTINO] [varchar](50) NULL,
	[CANTIDAD] [int] NULL,
	[DOC_REF_1] [varchar](50) NULL,
	[DOC_REF_2] [varchar](50) NULL,
	[DOC_REF_3] [varchar](50) NULL,
	[DOC_REF_4] [varchar](50) NULL,
	[DOC_REF_5] [varchar](50) NULL,
	[FECHA_TRANSACCION] [date] NULL,
 CONSTRAINT [PK_MOV_INVENTARIO] PRIMARY KEY CLUSTERED 
(
	[COD_CIA] ASC,
	[COMPANIA_VENTA_3] ASC,
	[ALMACEN_VENTA] ASC,
	[TIPO_MOVIMIENTO] ASC,
	[TIPO_DOCUMENTO] ASC,
	[NRO_DOCUMENTO] ASC,
	[COD_ITEM_2] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE PROCEDURE [dbo].[SP_ACTUALIZAR_MOVIMIENTO_INV]
	@COD_CIA varchar(5),
	@COMPANIA_VENTA_3 varchar(5),
	@ALMACEN_VENTA varchar(10),
	@TIPO_MOVIMIENTO varchar(2),
	@TIPO_DOCUMENTO varchar(2),
	@NRO_DOCUMENTO varchar(50),
	@COD_ITEM_2 varchar(50),
	@PROVEEDOR varchar(100),
	@ALMACEN_DESTINO varchar(50),
	@CANTIDAD int,
	@DOC_REF_1 varchar(50),
	@DOC_REF_2 varchar(50),
	@DOC_REF_3 varchar(50),
	@DOC_REF_4 varchar(50),
	@DOC_REF_5 varchar(50)
AS
BEGIN
	
	UPDATE [dbo].[MOV_INVENTARIO]
	SET [PROVEEDOR] = @PROVEEDOR
      ,[ALMACEN_DESTINO] = @ALMACEN_DESTINO
      ,[CANTIDAD] = @CANTIDAD
      ,[DOC_REF_1] = @DOC_REF_1
      ,[DOC_REF_2] = @DOC_REF_2
      ,[DOC_REF_3] = @DOC_REF_3
      ,[DOC_REF_4] = @DOC_REF_4
      ,[DOC_REF_5] = @DOC_REF_5
	WHERE	COD_CIA = @COD_CIA
	AND		COMPANIA_VENTA_3 = @COMPANIA_VENTA_3
	AND		ALMACEN_VENTA = @ALMACEN_VENTA
	AND		TIPO_MOVIMIENTO = @TIPO_MOVIMIENTO
	AND		TIPO_DOCUMENTO = @TIPO_DOCUMENTO
    AND		NRO_DOCUMENTO = @NRO_DOCUMENTO 
    AND		COD_ITEM_2 = @COD_ITEM_2

END
GO


CREATE PROCEDURE [dbo].[SP_ELIMINAR_MOVIMIENTO_INV]
	@COD_CIA varchar(5)
AS
BEGIN
	
	DELETE [dbo].[MOV_INVENTARIO]
	WHERE	COD_CIA = @COD_CIA

END
GO

CREATE PROCEDURE [dbo].[SP_INSERTAR_MOVIMIENTO_INV]
	@COD_CIA varchar(5),
	@COMPANIA_VENTA_3 varchar(5),
	@ALMACEN_VENTA varchar(10),
	@TIPO_MOVIMIENTO varchar(2),
	@TIPO_DOCUMENTO varchar(2),
	@NRO_DOCUMENTO varchar(50),
	@COD_ITEM_2 varchar(50),
	@PROVEEDOR varchar(100),
	@ALMACEN_DESTINO varchar(50),
	@CANTIDAD int,
	@DOC_REF_1 varchar(50),
	@DOC_REF_2 varchar(50),
	@DOC_REF_3 varchar(50),
	@DOC_REF_4 varchar(50),
	@DOC_REF_5 varchar(50)
AS
BEGIN
	
	INSERT INTO [dbo].[MOV_INVENTARIO]
           ([COD_CIA]
           ,[COMPANIA_VENTA_3]
           ,[ALMACEN_VENTA]
           ,[TIPO_MOVIMIENTO]
           ,[TIPO_DOCUMENTO]
           ,[NRO_DOCUMENTO]
           ,[COD_ITEM_2]
           ,[PROVEEDOR]
           ,[ALMACEN_DESTINO]
           ,[CANTIDAD]
           ,[DOC_REF_1]
           ,[DOC_REF_2]
           ,[DOC_REF_3]
           ,[DOC_REF_4]
           ,[DOC_REF_5]
           ,[FECHA_TRANSACCION])
     VALUES
           (@COD_CIA,
           @COMPANIA_VENTA_3,
           @ALMACEN_VENTA,
           @TIPO_MOVIMIENTO,
           @TIPO_DOCUMENTO,
           @NRO_DOCUMENTO,
           @COD_ITEM_2,
           @PROVEEDOR,
           @ALMACEN_DESTINO,
           @CANTIDAD,
           @DOC_REF_1,
           @DOC_REF_2,
           @DOC_REF_3,
           @DOC_REF_4,
           @DOC_REF_5,
           CURRENT_TIMESTAMP
		   )

END
GO


CREATE PROCEDURE [dbo].[SP_LISTAR_MOVIMIENTO_INV]
	@FECINICIO VARCHAR(10) = NULL,
	@FECFINAL VARCHAR(10) = NULL,
	@TIPMOVIMIENTO VARCHAR(2) = NULL,
	@NRODOCUMENTO VARCHAR(50) = NULL

AS
BEGIN
	
	Select *
	From dbo.MOV_INVENTARIO
	Where (@FECINICIO IS NULL OR FECHA_TRANSACCION >= CONVERT(DATETIME,@FECINICIO,103)) 
	And (@FECFINAL IS NULL OR FECHA_TRANSACCION  <= CONVERT(DATETIME,@FECFINAL,103))
	And	(@TIPMOVIMIENTO IS NULL OR [TIPO_MOVIMIENTO] = @TIPMOVIMIENTO)
	And	(@NRODOCUMENTO IS NULL OR [NRO_DOCUMENTO] = @NRODOCUMENTO)

END

GO

CREATE PROCEDURE [dbo].[SP_LISTAR_MOVIMIENTO_INV_CODIGO]
	@CODIGO_CIA VARCHAR(5) = NULL
AS
BEGIN
	
	Select *
	From dbo.MOV_INVENTARIO
	Where [COD_CIA] = @CODIGO_CIA

END
